#!/usr/bin/env bash
_logger() {
    logger -t run_after_docker $1
}

_logger START
_init_configs() {
    mkdir -p /opt/config
    mkdir -p /opt/nginx

    local files=("teleport.yml" "nginx.tmpl")
    local uri="https://raw.githubusercontent.com/sdwandemo/service/master/config"
    local dir="/opt/config"

    for i in ${files[@]}; do
        rm -rf $dir/$i
        curl $uri/$i > $dir/$i
        chmod 0644 $dir/$i
        _logger "wrote $dir/$i"
    done
}

_init_configs
_logger DONE
